openapi: 3.0.0
info:
  title: Demo Mail Service
  version: 0.0.1
  description: |
    Сервис Почтальон 
    осуществляет доставку писем от одного зарегистрированного пользователя к другому,
    предоставляет доступ к 
      истории переписки между двумя заданными пользователями, 
      спискам отправленных, полученных и непрочитанных 
      заданным пользователем сообщений.
    Он предоставляет возможность получателю 
      отметить сообщение как прочитанное,
      группировать сообщения по тегам, 
      а также искать письма по содержимому в теле сообщения.
servers:
  - url: /api/v1/
paths:
  /ops/ping:
    get:
      tags: [Monitoring]
      summary: Checks if server is alive
      description: Returns 'pong' if server is alive and ok, otherwise throws an error.
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: pong
  /mailboxes:
    post:
      tags: [Mailboxes]
      summary: Creates new mailbox.
      description: Creates new mailbox account with a given email as login.
      requestBody:
        description: Mailbox draft to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MailboxDraftView'
      responses:
        200:
          description: Mailbox created.
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/MailboxView'
        400:
          description: Mailbox address already in use.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorView'

components:
  schemas:

    GeneralErrorView:
      type: object
      properties:
        code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string

    MailboxDraftView:
      type: object
      properties:
        publicAddress:
          type: string
          format: email
      
    MailboxView:
      type: object
      properties:
        id:
          type: integer
          format: int32
        publicAddress:
          type: string
          format: email
