@startuml "Model"

class Mailbox {
  id: Mailbox.Id
  publicAddress: Mailbox.Address
}

class Message {
  id: Message.Id
  senderId: Mailbox.Id
  recieverId: Mailbox.Id
  body: Message.Body
}

Message --> Mailbox

@enduml